included:
  - WalletOS
  - WalletOSTests
  - WalletOSUITests

excluded:
  - WalletOS.xcodeproj
  - DerivedData
  - .build

opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - first_where
  - force_unwrapping
  - redundant_nil_coalescing
  - toggle_bool
  - unneeded_parentheses_in_closure_argument

line_length:
  warning: 120
  error: 160
  ignores_comments: true
  ignores_urls: true

identifier_name:
  min_length: 2
  excluded:
    - id
    - to
    - i

type_name:
  min_length: 3
  max_length:
    warning: 45
    error: 60

force_cast: error
force_try: error
